#ifndef CONSTANTS_H
#define CONSTANTS_H

#define V4L2_MAX_BUFFERS 4
#define VIDEO_DEVICE_PATH "/dev/video0"
#define BYTES_PER_YUYV_PIXEL 2U
#define RGB_CHANNELS 4
#define ALPHA_BYTE_VALUE 255U
#define INVALID_FILE_DESCRIPTOR -1
#define SIMD_BLOCK_BYTE_SIZE 16
#define SIMD_BLOCK_BYTE_SIZE_X2 32
#define SIMD_BLOCK_BYTE_SIZE_X3 48
#define PIXELS_PER_SIMD_BLOCK 16

#endif  // CONSTANTS_H
